# Generated by Django 2.0.6 on 2018-06-25 02:55

import app.validacao
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogada',
            name='vizinhos',
            field=models.CharField(max_length=1, null=True, validators=[app.validacao.validate_even]),
        ),
    ]
