# Generated by Django 2.0.6 on 2018-06-23 23:46

import app.validacao
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogada',
            name='coluna',
            field=models.CharField(max_length=1, validators=[app.validacao.validate_even]),
        ),
        migrations.AlterField(
            model_name='jogada',
            name='linha',
            field=models.CharField(max_length=1, validators=[app.validacao.validate_even]),
        ),
    ]
